// 内置暗色主题「Velotype」：色值移植自 velotype `theme/theme.rs` 的 default_theme()。
// token 名称与 velotype 主题 JSON 接口保持一致（snake_case）。

export default {
  id: 'velotype',
  name: 'Velotype',
  builtin: true,
  theme: {
    colors: {
      editor_background: '#191919',
      source_mode_block_bg: '#313131',
      comment_bg: '#fbbf2426',
      text_default: '#f0efed',
      text_link: '#60a5fa',
      text_placeholder: '#999999',
      text_h1: '#f0efed',
      text_h2: '#f0efed',
      text_h3: '#f0efed',
      text_h4: '#f0efed',
      text_h5: '#f0efed',
      text_h6: '#f0efed',
      text_strong: '#f0efed',
      text_em: '#f0efed',
      text_strikethrough: '#f0efed',
      mark_bg: '#ffcc0059',
      mark_text: '#f0efed',
      kbd_bg: '#313131',
      kbd_text: '#f0efed',
      kbd_border: '#71717a',
      list_marker: '#999999',
      table_header_text: '#f0efed',
      task_checkbox_border: '#71717a',
      task_checkbox_bg: 'transparent',
      task_checkbox_checked_bg: '#f0efed',
      task_checkbox_check: '#18181b',
      scrollbar_thumb: '#d1d5dbd8',
      code_syntax_comment: '#565f89',
      code_syntax_keyword: '#bb9af7',
      code_syntax_string: '#9ece6a',
      code_syntax_number: '#ff9e64',
      code_syntax_type: '#2ac3de',
      code_syntax_function: '#7aa2f7',
      code_syntax_constant: '#ffd166',
      code_syntax_variable: '#e5e9f0',
      code_syntax_property: '#7dcfffcc',
      code_syntax_operator: '#89ddff',
      code_syntax_punctuation: '#9aa5ce',
      text_quote: '#d1d5db',
      border_quote: '#6b7280',
      callout_note_bg: '#94a3b81f',
      callout_note_border: '#94a3b4',
      callout_tip_bg: '#1d4ed81f',
      callout_tip_border: '#60a5fa',
      callout_important_bg: '#a78bfa1f',
      callout_important_border: '#a78bfa',
      callout_warning_bg: '#fb71851f',
      callout_warning_border: '#fb7185',
      callout_caution_bg: '#dc26261f',
      callout_caution_border: '#f87171',
      footnote_badge_text: '#d4d4d8cc',
      separator_color: '#71717a',
      code_bg: '#23272e',
      code_text: '#e5e7eb',
      table_border: '#3f3f46',
      table_header_bg: '#232326',
      table_cell_bg: '#1d1d20',
      image_placeholder_bg: '#202024',
      image_placeholder_border: '#52525b',
      image_placeholder_text: '#d4d4d8',
      cursor: '#f0efed',
      selection: '#1c3651',
      status_bar_background: '#1c1c1f',
      status_bar_text: '#d4d4d8cc',
      status_bar_text_dim: '#71717a',
      status_bar_button_hover: '#3f3f46',
    },
    typography: {
      font_family:
        '-apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
      code_font_family: 'Consolas, "JetBrains Mono", Menlo, "Courier New", monospace',
      text_size: 18,
      text_line_height: 1.6,
      h1_size: 32,
      h1_weight: 'bold',
      h2_size: 24,
      h2_weight: 'bold',
      h3_size: 20,
      h3_weight: 'semibold',
      h4_size: 18,
      h4_weight: 'semibold',
      h5_size: 16,
      h5_weight: 'semibold',
      h6_size: 14,
      h6_weight: 'semibold',
      code_size: 15,
      script_scale: 0.75,
      math_cjk_font: 'C:\\Windows\\Fonts\\simsun.ttc#SimSun',
    },
    dimensions: {
      editor_padding: 24,
      content_max_width: null,
      quote_border_width: 3,
      callout_radius: 10,
      code_bg_radius: 4,
    },
  },
};
