// 内置暗色主题「Mdmdt Dark」（id 保持 velotype，兼容已存储的主题选择与 baseThemeId 继承）。
// 配色与排版参考 Typora 主题 Mdmdt（https://github.com/cayxc/Mdmdt，Apache-2.0）的暗色方案：
// 背景 #181a1d / 副背景 #22262b、主色 #3e69d7、强调橙 #f59102、标题 2px 字距、
// h1 底部分隔线、引用蓝底圆角、表格斑马纹。token 名称与 velotype 主题 JSON 接口一致，
// Mdmdt 特有的扩展 token（quote_bg 等）供 blocks 引用，自定义主题可同法新增。

import { mathCjkFontSpec } from '../utils/platform.js';

export default {
  id: 'velotype',
  name: 'Mdmdt Dark',
  builtin: true,
  theme: {
    colors: {
      editor_background: '#181a1d',
      source_mode_block_bg: '#22262b',
      comment_bg: '#667c8926',
      text_default: '#d0d0d0',
      text_link: '#3e69d7',
      text_placeholder: '#667c89',
      text_h1: '#d0d0d0',
      text_h2: '#d0d0d0',
      text_h3: '#d0d0d0',
      text_h4: '#d0d0d0',
      text_h5: '#d0d0d0',
      text_h6: '#d0d0d0',
      text_strong: '#cfdfff',
      text_em: '#d0d0d0',
      text_strikethrough: '#667c89',
      mark_bg: '#3e69d7',
      mark_text: '#fafafa',
      // kbd 与亮色同语义（反转表面色：暗底浅字 ↔ 浅底深字），替代原橙色（过重）
      kbd_bg: '#d0d0d0',
      kbd_text: '#181a1d',
      kbd_border: 'transparent',
      list_marker: '#667c89',
      table_header_text: '#d0d0d0',
      task_checkbox_border: '#464b50',
      task_checkbox_bg: 'transparent',
      task_checkbox_checked_bg: '#3e69d7',
      task_checkbox_check: '#ffffff',
      scrollbar_thumb: '#464b50',
      scrollbar_track: 'transparent',
      code_syntax_comment: '#667c89',
      code_syntax_keyword: '#bb59fd',
      code_syntax_string: '#02be74',
      code_syntax_number: '#f59102',
      code_syntax_type: '#6083ff',
      code_syntax_function: '#3876eb',
      code_syntax_constant: '#fa5336',
      code_syntax_variable: '#f4395d',
      code_syntax_property: '#1b9f72',
      code_syntax_operator: '#40d7ec',
      code_syntax_punctuation: '#667c89',
      text_quote: '#d0d0d0',
      border_quote: '#3e69d7',
      callout_note_bg: '#3e69d71f',
      callout_note_border: '#3e69d7',
      callout_tip_bg: '#03b7361f',
      callout_tip_border: '#03b736',
      callout_important_bg: '#8250df1f',
      callout_important_border: '#8250df',
      callout_warning_bg: '#f591021f',
      callout_warning_border: '#f59102',
      callout_caution_bg: '#e30f2e1f',
      callout_caution_border: '#e30f2e',
      footnote_badge_text: '#3e69d7',
      separator_color: '#464b50',
      code_bg: '#22262b',
      code_text: '#bbc7fd',
      table_border: '#464b50',
      table_header_bg: '#22262b',
      table_cell_bg: '#181a1d',
      image_placeholder_bg: '#22262b',
      image_placeholder_border: '#464b50',
      image_placeholder_text: '#667c89',
      cursor: '#d0d0d0',
      selection: '#f5910266',
      status_bar_background: '#181a1d',
      status_bar_border: '#464b50',
      tab_indicator: '#3e69d7',
      status_bar_text: '#d0d0d0',
      status_bar_text_dim: '#667c89',
      status_bar_button_hover: '#22262b',
      // ---- Mdmdt 扩展 token（被下方 blocks 引用；自定义主题可同法新增）----
      quote_bg: '#3e69d71f',
      inline_code_bg: '#3e69d74d',
      inline_code_text: '#bbc7fd',
      link_hover: '#f59102',
      strikethrough_line: '#e30f2e',
      table_zebra_bg: '#22262b',
    },
    typography: {
      font_family:
        '"PingFang SC", "Microsoft YaHei UI", "Microsoft YaHei", Arial, "Helvetica Neue", Helvetica, sans-serif',
      code_font_family:
        '"JetBrains Mono", "Source Code Pro", "Fira Code", Consolas, Inconsolata, "Cascadia Code", Monaco, "Ubuntu Mono", monospace',
      text_size: 16,
      text_line_height: 1.6,
      h1_size: 32,
      h1_weight: 'bold',
      h2_size: 28,
      h2_weight: 'bold',
      h3_size: 24,
      h3_weight: 'bold',
      h4_size: 20,
      h4_weight: 'bold',
      h5_size: 18,
      h5_weight: 'bold',
      h6_size: 16,
      h6_weight: 'bold',
      code_size: 14,
      script_scale: 0.75,
      math_cjk_font: mathCjkFontSpec,
    },
    dimensions: {
      editor_padding: 32,
      content_max_width: null,
      quote_border_width: 4,
      callout_radius: 8,
      code_bg_radius: 8,
      scrollbar_width: 8,
    },
    // Mdmdt 版式特征：标题 2px 字距、h1 底部分隔线、正文 0.6px 字距、引用蓝底圆角、
    // 表格斑马纹、链接去下划线（悬停橙色+下划线）、行内代码蓝底、mark/kbd 圆角填充
    blocks: {
      heading: {
        letterSpacing: '2px',
        lineHeight: 1.5,
        margin: '32px 0 18px',
        h1: {
          borderBottom: '1px solid var(--t-separator-color)',
          paddingBottom: '8px',
        },
      },
      paragraph: { letterSpacing: '0.6px' },
      quote: {
        letterSpacing: '0.6px',
        background: 'var(--t-quote-bg)',
        borderRadius: '8px',
        padding: '16px',
      },
      bulletedListItem: { letterSpacing: '0.6px' },
      numberedListItem: { letterSpacing: '0.6px' },
      taskListItem: { letterSpacing: '0.6px' },
      table: {
        borderRadius: '8px',
        'tbody tr:nth-child(even) td': { background: 'var(--t-table-zebra-bg)' },
      },
      link: {
        textDecoration: 'none',
        fontWeight: 500,
        ':hover': { color: 'var(--t-link-hover)', textDecoration: 'underline' },
      },
      inlineCode: {
        background: 'var(--t-inline-code-bg)',
        color: 'var(--t-inline-code-text)',
        padding: '3px 5px',
      },
      strong: { fontWeight: 800 },
      strikethrough: { textDecorationColor: 'var(--t-strikethrough-line)' },
      mark: { padding: '0 4px', borderRadius: '5px' },
      kbd: { border: 'none', borderRadius: '5px', padding: '0 6px', fontWeight: 900 },
      taskCheckbox: { width: '14px', height: '14px', borderWidth: '1px', borderRadius: '3px' },
    },
  },
};
